{
 "title": "Serve LLM Dashboard",
 "tags": [ "rayVersion:2.55.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "vllm_model_name",
    "label": "vLLM Model Name",
    "query": {
     "query": "label_values(ray_vllm:request_prompt_tokens_sum{}, model_name)"
    }
   },
   {
    "name": "workerid",
    "label": "Worker ID",
    "query": {
     "query": "label_values(ray_vllm:request_prompt_tokens_sum{}, WorkerId)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter_total{}, deployment)"
    }
   },
   { "name": "interval", "label": "Interval" }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / s",
   "type": "graph",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment, replica) (rate(ray_serve_deployment_request_counter_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", , deployment=~\"$deployment\"}[$interval]))",
     "legendFormat": "{{deployment}}: {{replica}}"
    },
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", , deployment=~\"$deployment\"}[$interval]))",
     "legendFormat": "Total QPS"
    }
   ]
  },
  {
   "title": "Prompt Tokens/s",
   "type": "graph",
   "description": "Number of tokens processed per second",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "tokens/s" } },
   "yaxes": [
    { "format": "tokens/s" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (rate(ray_vllm_request_prompt_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    },
    {
     "expr": "sum(rate(ray_vllm_request_prompt_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Generation Tokens/s",
   "type": "graph",
   "description": "Number of tokens processed per second",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "tokens/s" } },
   "yaxes": [
    { "format": "tokens/s" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (rate(ray_vllm_generation_tokens_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    },
    {
     "expr": "sum(rate(ray_vllm_generation_tokens_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TPOT -- Mean",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "TPOT -- P50",
   "type": "graph",
   "gridPos": { "x": 8, "y": 10, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.5,\n    sum by (le, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "TPOT -- P90",
   "type": "graph",
   "gridPos": { "x": 16, "y": 10, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.9,\n    sum by (le, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "TTFT -- Mean",
   "type": "graph",
   "gridPos": { "x": 0, "y": 18, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_time_to_first_token_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "TTFT -- P50",
   "type": "graph",
   "gridPos": { "x": 8, "y": 18, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.5,\n    sum by (le, WorkerId) (rate(ray_vllm_time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "TTFT -- P90",
   "type": "graph",
   "gridPos": { "x": 16, "y": 18, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.9,\n    sum by (le, WorkerId) (rate(ray_vllm_time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Request Latency -- Mean",
   "type": "graph",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "x": 0, "y": 26, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Request Latency -- P50",
   "type": "graph",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "x": 8, "y": 26, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.5,\n    sum by (le, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Request Latency -- P90",
   "type": "graph",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "x": 16, "y": 26, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.9,\n    sum by (le, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cache Utilization",
   "type": "graph",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "x": 0, "y": 35, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (ray_vllm_kv_cache_usage_perc{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", })\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "GPU KV Cache Hit Rate",
   "type": "graph",
   "gridPos": { "x": 12, "y": 35, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ((sum by(WorkerId) (rate(ray_vllm_prefix_cache_hits_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) / sum by(WorkerId) (rate(ray_vllm_prefix_cache_queries_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))) and on(WorkerId) (sum by(WorkerId) (rate(ray_vllm_prefix_cache_queries_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  { "title": "Request Length", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Prompt Length -- Mean",
   "type": "graph",
   "gridPos": { "x": 0, "y": 44, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_prompt_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_request_prompt_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_prompt_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Prompt Length -- P50",
   "type": "graph",
   "gridPos": { "x": 8, "y": 44, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.5,\n    sum by (le, WorkerId) (rate(ray_vllm_request_prompt_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_prompt_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Prompt Length -- P90",
   "type": "graph",
   "gridPos": { "x": 16, "y": 44, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.9,\n    sum by (le, WorkerId) (rate(ray_vllm_request_prompt_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_prompt_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Generation Length -- Mean",
   "type": "graph",
   "gridPos": { "x": 0, "y": 52, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_generation_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_request_generation_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_generation_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Generation Length -- P50",
   "type": "graph",
   "gridPos": { "x": 8, "y": 52, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.5,\n    sum by (le, WorkerId) (rate(ray_vllm_request_generation_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_generation_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Generation Length -- P90",
   "type": "graph",
   "gridPos": { "x": 16, "y": 52, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.9,\n    sum by (le, WorkerId) (rate(ray_vllm_request_generation_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_request_generation_tokens_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Scheduler: Running",
   "type": "graph",
   "gridPos": { "x": 0, "y": 61, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (ray_vllm_num_requests_running{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", })\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Scheduler: Swapped",
   "type": "graph",
   "gridPos": { "x": 8, "y": 61, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (ray_vllm_num_requests_swapped{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", })\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Scheduler: Waiting",
   "type": "graph",
   "gridPos": { "x": 16, "y": 61, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (ray_vllm_num_requests_waiting{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", })\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "graph",
   "description": "Number of finished requests by their finish reason.",
   "gridPos": { "x": 0, "y": 69, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(finished_reason, WorkerId) (increase(ray_vllm_request_success_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{finished_reason}} — {{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "graph",
   "gridPos": { "x": 12, "y": 69, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (rate(ray_vllm_request_queue_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Prefill Time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 77, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (rate(ray_vllm_request_prefill_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Decode Time",
   "type": "graph",
   "gridPos": { "x": 12, "y": 77, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (rate(ray_vllm_request_decode_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  { "title": "NIXL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "NIXL: Transfer Latency",
   "type": "graph",
   "description": "Average NIXL KV cache transfer latency in milliseconds.",
   "gridPos": { "x": 0, "y": 86, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_nixl_xfer_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_nixl_xfer_time_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    * 1000\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_nixl_xfer_time_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "NIXL: Transfer Throughput",
   "type": "graph",
   "description": "NIXL KV cache transfer throughput in GB/s.",
   "gridPos": { "x": 8, "y": 86, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "yaxes": [
    { "format": "GBs" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_nixl_bytes_transferred_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_nixl_xfer_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    / 1024 / 1024 / 1024\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_nixl_xfer_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "NIXL: Transfer Rate",
   "type": "graph",
   "description": "Number of NIXL KV cache transfers per second.",
   "gridPos": { "x": 16, "y": 86, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (rate(ray_vllm_nixl_xfer_time_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "NIXL: Avg Post Time",
   "type": "graph",
   "description": "Average time to post/initiate a NIXL transfer in milliseconds.",
   "gridPos": { "x": 0, "y": 94, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by(WorkerId) (rate(ray_vllm_nixl_post_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    /\n    sum by(WorkerId) (rate(ray_vllm_nixl_post_time_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n    * 1000\n  )\n  and on(WorkerId)\n  (\n    sum by(WorkerId) (rate(ray_vllm_nixl_post_time_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) > 0\n  )\n)\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "NIXL: KV Transfer Failures",
   "type": "graph",
   "description": "Number of failed NIXL KV cache transfers. Any non-zero value is concerning and indicates RDMA transfer errors.",
   "gridPos": { "x": 8, "y": 94, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (increase(ray_vllm_nixl_num_failed_transfers{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "NIXL: KV Expired Requests",
   "type": "graph",
   "description": "Number of requests whose KV blocks expired before decode consumed them. Spikes indicate prefill is outrunning decode or the timeout is too short.",
   "gridPos": { "x": 16, "y": 94, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(WorkerId) (increase(ray_vllm_nixl_num_kv_expired_reqs_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n* on(WorkerId) group_left(deployment, replica)\nmax by(WorkerId, deployment, replica) (ray_serve_deployment_request_counter_total{, deployment=~\"$deployment\"} * 0 + 1)",
     "legendFormat": "{{deployment}}: {{replica}}"
    }
   ]
  },
  {
   "title": "Token Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tokens Last 24 Hours",
     "type": "stat",
     "gridPos": { "x": 0, "y": 103, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])))",
       "legendFormat": "Input: {{model_name}}"
      },
      {
       "expr": "(sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1d])))",
       "legendFormat": "Generated: {{model_name}}"
      }
     ]
    },
    {
     "title": "Tokens Last Hour",
     "type": "stat",
     "gridPos": { "x": 12, "y": 103, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1h]))",
       "legendFormat": "Input: {{model_name}}"
      },
      {
       "expr": "sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1h]))",
       "legendFormat": "Generated: {{model_name}}"
      }
     ]
    },
    {
     "title": "Ratio Input:Generated Tokens Last 24 Hours",
     "type": "stat",
     "gridPos": { "x": 0, "y": 111, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])) / sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1d]))",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Distribution of Requests Per Model Last 24 Hours",
     "type": "piechart",
     "gridPos": { "x": 12, "y": 111, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "Requests" } },
     "yaxes": [
      { "format": "Requests" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1d]))",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Peak Tokens Per Second Per Model Last 24 Hours",
     "type": "stat",
     "gridPos": { "x": 0, "y": 119, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(sum by (model_name) (rate(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[2m]))[24h:1m])",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Tokens Per Model Last 24 Hours",
     "type": "stat",
     "gridPos": { "x": 12, "y": 119, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])) + sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1d]))",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Avg Total Tokens Per Request Last 7 Days",
     "type": "gauge",
     "gridPos": { "x": 0, "y": 127, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) +\nsum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w]))) / sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "{{ model_name}}"
      }
     ]
    },
    {
     "title": "Requests Per Model Last Week",
     "type": "gauge",
     "gridPos": { "x": 12, "y": 127, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "{{ model_name}}"
      }
     ]
    },
    {
     "title": "Tokens Per Model Last 7 Days",
     "type": "gauge",
     "gridPos": { "x": 0, "y": 135, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "In: {{ model_name}}"
      },
      {
       "expr": "sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "Out: {{ model_name }}"
      }
     ]
    },
    {
     "title": "Avg Total Tokens Per Request Per Model Last 7 Days",
     "type": "gauge",
     "gridPos": { "x": 12, "y": 135, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) + sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w])))/ sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "{{ model_name}}"
      }
     ]
    },
    {
     "title": "Tokens Per Request Per Model Last 7 Days",
     "type": "gauge",
     "gridPos": { "x": 0, "y": 143, "w": 12, "h": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) / sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "In: {{ model_name}}"
      },
      {
       "expr": "sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w])) / sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
       "legendFormat": "Out: {{ model_name}}"
      }
     ]
    }
   ]
  }
 ]
}